### ISSUE TITLE
Add address validation error

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#101]
Recommended from Ben : if clicked without entering a known location, show an alert with a helptext reminder of the search format required. For example: 

![Screen Shot 2019-07-16 at 1 54 56 PM](https://user-images.githubusercontent.com/6900926/61329085-53f3c980-a7d1-11e9-91f9-3c99d3b6cacb.png)

**Comment by Jkrzy** [comment]
Waiting on content/messaging review in #141

**Comment by hursey013** [comment]
@Jkrzy Ok to close?
