### ISSUE TITLE
Implement new design for content section on homepage

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#107]
Awaiting final design after review from team and I will add the story here

**Comment by nickttng** [comment]
Assets for representative icons are in the project drive (I'm unable to create a direct shared link)

- SVGs are created and should be used primarily
- PNGs sized in both 1x and 2x (retina); used as backup for SVGs if SVGs fail to render

Notes:
- In the SVGs, the `<title>` and `<desc>` are created for accessibility purpose. Below are the current titles and descriptions, but feel free to suggest content change to improve clarity
  - Addiction: `<title>Decision-Making</title>` and `<desc>A cyclical movement in the head</desc>`
  - Treatment: `<title>Treatment assistance</title>` and `<desc>A hand receiving a treatment</desc>`
  - Payment: `<title>Payment document</title>` and `<desc>A billing statement with checkmark</desc>`


- When being implemented, the icons should be resized to ~100px area (height / width), but use best judgement and test in various viewports

**Comment by nickttng** [comment]
Screenshots of how content section should generally appear on desktop/large and mobile/small-portrait
<img width="475" alt="Screen Shot 2019-07-18 at 11 49 23 AM" src="https://user-images.githubusercontent.com/6327082/61476232-300bc180-a952-11e9-93c9-bce83d97a8db.png">
