### ISSUE TITLE
Update What to expect - "home page" of info content (lede + content)

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#109]
From @amandacostello: 

(Covered in PR #110)

- [x] Update homepage under "What to Expect" - "Treatment works, help is available, and people recover every day."
- [x] Update "What to Expect" landing page: Lede: Treatment works, help is available, and people recover every day."
- [x] Update Intro para: "Beginning recovery can be overwhelming and intimidating. While everyone's path to recovery is unique, there are certain things you can expect and be ready for when you start.
- [x] Update secondary para: There is help. From understanding more about addiction and treatment options, to being ready to navigate insurance and payment, this information can help you feel more confident as you take the next step to finding treatment.
- [x] Add lede/subtitle on homepage under What to expect

We should also:
- [x] Link to the Getting started content section in top nav
- [x] Remove subtopic from Getting Started section (or, if easier, rewrite that so it's not duplicative)

**Comment by hursey013** [comment]
Closed with https://github.com/18F/samhsa-prototype/pull/110
