### ISSUE TITLE
Deep linking isn't working / pages won't refresh

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#119]
Saw this manifest in three ways:
1. When I navigate to https://findtreatmentbeta.18f.gov/content/understanding-addiction and refresh, the page reloads blank
2. When I try to go to https://findtreatmentbeta.18f.gov/content/understanding-addiction directly, the page won't load
3. When I click an external link (AA, NA, etc) and click back to come back to the content, I land on a blank page. 

Steps to reproduce:
- Navigate through the site to any info content page
- Hit refresh

Similarly (but maybe separate / expected due to our limitations):
4. When I refresh the results page, I get a no results message but I think it's because my location gets cleared. 
5. When I am on a details page and refresh, I get sent back to the home page.

**Comment by hursey013** [comment]
Fixed with https://github.com/18F/samhsa-prototype/pull/124

4&5 are expected behavior.
