### ISSUE TITLE
Update default error messaging

### ISSUE THREAD

**Issue by NorahMaki** [18F/samhsa-prototype#12]
Once possible, update default Federalist error messaging to be similar to No Results page, so as not to dead-end people.

**Comment by allisonnorman** [comment]
@amandacostello has drafted content for the default 404 error messaging: https://docs.google.com/document/d/1gnoON2VLdI5HBVG1dcghdfedzwuj1KJed62b1-71Oz8/edit#heading=h.g26uh4bg1ygw
