### ISSUE TITLE
[object Object] is printing in source on header

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#120]
Not sure if this is affecting anything but if you view source for the text Treatment Finder in header, [object Object] shows up. My husband saw this and I may not be explaining it perfectly but wanted to let you know in case there are any unintended effects. 

![Screen Shot 2019-07-18 at 3 29 48 PM](https://user-images.githubusercontent.com/6900926/61496384-e54d7200-a970-11e9-930d-528f8d85aa35.png)

**Comment by hursey013** [comment]
This is definitely peculiar, but likely just a side effect of the styling utilities we are using. It should not impact the end user experience, but it's something to look at when we do some clean up / another pass at styling.
