### ISSUE TITLE
Implement SU/MH-specific filters

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#126]
Background: Mental health and substance use are closely tied together. SAMHSA's treatment locator currently returns both facilities that treat both SU and MH, and they are classified as MH or SU based on which survey they have filled out. 

While our focus during the engagement has been on substance use, we want to understand how people are engaging with these filters in order to build a longer term strategy (to either bring in MH facilities, to create a separate locator, etc).  This testing approach has trade offs, as the content and branding of the site is on substance use treatment. For this reason, we have decided to only include co-occurring (SU+MH) and a broad MH services filter to get a signal on whether people are looking for mental health support through this tool.  

User stories:
1. As a visitor looking for substance use treatment, I should not be shown mental health facilities returned by default unless I select a mental-health specific type of care filter (mental health or co-occurring) so that I do not reach out to a facility that might not specialize in providing substance use treatment disorder. 
2. As a visitor looking for co-occurring treatment, I should be able to select co-occurring under type of care and see both mental health and substance use facilities so that I can connect with a treatment providers who can support my MH+SU-specific needs.
3. As a visitor looking for mental health services, I should be able to find mental health facilities under type of care. 
4. As a visitor looking for psychiatric emergency walk in services, I should be able to find mental health facilities under type of care 
5. As a visitor not sure of what I'm looking for, I should be able to read about co-occurring and mental health services types of care in the informational content - @amandacostello, Kait

Summary (alternately, see notes [here](https://docs.google.com/document/d/14S88KXIqK4VeLheoqmRgXa-OiHo3rpFGRqW3u3Fs7xk/edit#heading=h.5cj4phf568f8) 
1. Remove mental health facilities in default search. Unless a visitor interacts with one of the below filters, they should not see mental health facilities returned. 
2. Adjust how results are returned for following filters in the 'type of care' dropdown:
- 'Co-occurring mental health and substance use treatment' (service codes, CO, SA, MH)  Return either SU or MH results with the service code CO
- 'Mental health services only' (service code - MH): Return all MH services only (no SU)
- Psychiatric emergency walk-in services (service code - PSY): This filter is MH-only. If SU is removed from default search, this will need to be set up to return MH results via the filter query.

**Comment by hursey013** [comment]
For posterity, 'Co-occurring mental health and substance use treatment' would be `sType: BOTH, sCodes: CO`

**Comment by allisonnorman** [comment]
@BrooklynHopkins - Can you and Kait sign off on this so Brian can get started? We want to make sure we're all on the same page so we don't have to reverse the changes mid-flight. Thanks!

**Comment by allisonnorman** [comment]
@hursey013 - I confirmed with @BrooklynHopkins and Kait that we're on the same page with this. Still finalizing some other details (whether we swap out the assessment option with 'not sure) but feel free to get started on the filter functionality changes in this issue when you can. I'll track the others separately. Thanks!

**Comment by Jkrzy** [comment]
Attempting to summarive here for my understanding.

New Type of Care option | Notes 
---|---|
Co-occurring mental health and substance use treatment| Show BOTH w/  CO service code
Mental health services only| Show ALL MH
Psychiatric emergency walk-in services| Show only MH w/ emergency walk-in service code

**Comment by Jkrzy** [comment]
Given our list of filters is limited, let's list those which would be impacted.

**Comment by BrooklynHopkins** [comment]
yes

**Comment by allisonnorman** [comment]
We are going to stick with the proposal above (my summary, and more concisely summarized in Joe's table), per @BrooklynHopkins. @hursey013 - Feel free to get started
