### ISSUE TITLE
Update home page design to incorporate 4th content box for mental health

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#133]
Based on SAMHSA leadership feedback, we need to incorporate aspects of mental health in our prototype to test with the public. This will include updates to info content, which we will want to link to from the homepage.

What we'll need from a design perspective from @nickttng: 
- A new icon for mental health box (we can use lorem ipsum for the content for now)
- Update sizing of all 4 boxes / update proportions, if needed

**Comment by hursey013** [comment]
I would love to see an alternative to adding a fourth box - to me, it feels veery cramped with four boxes, so perhaps there is a better way to display that information? The boxes are really just an artifact from rapid prototyping, so I don't think it's a pattern we need to follow if there are better options.

**Comment by nickttng** [comment]
@allisonnorman @hursey013 The mental health icon (SVG + PNGs labeled _what-to-expect-mental-health_ is now in the shared Drive: `9. Assets > Visual/UI > Icons > What to expect`

In addition, the new _what-to-expect-addiction.svg_ and PNGs (tangled brain) to swap out the old (cycle arrow)

Background context/convo in 🔒[Slack](https://gsa-tts.slack.com/archives/CGBQQ8KFD/p1564169848038300)

**Comment by hursey013** [comment]
Closed by https://github.com/18F/samhsa-prototype/pull/156
