### ISSUE TITLE
Focusing location filter breaks pagination

### ISSUE THREAD

**Issue by hursey013** [18F/samhsa-prototype#144]
Steps to reproduce:
- Conduct a search with a location that returns more than one page of results
- Before clicking a pagination link, click in and out of the location input box to clear it, but don't fill in a new location
- Now go and use one of the pagination links and observe that it no longer works correctly

**Comment by Jkrzy** [comment]
Is this still an issue? Having trouble reproducing it per the steps above.

**Comment by hursey013** [comment]
Yes, still an issue. I think the cause is that when you focus the location input it clears the value from the input box _and_ the redux store. We should probably just clear the input box and leave the value in the store so that it is still available to be sent along with subsequent endpoint requests.

**Comment by hursey013** [comment]
Upon further inspection I think this is actually the behavior we want, and since we have an upcoming issue in the backlog for searching as filters are toggled (rather than needing to press the submit button), I think implementing that will resolve this. Clearing the location will also clear the results, eliminating this issue.

**Comment by hursey013** [comment]
Resolved with https://github.com/18F/samhsa-prototype/pull/174
