### ISSUE TITLE
Advanced filters section: Move existing + add new filters

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#16]
In the advanced filter/"more" filters section, can you please add two new filters under language?

**Special programs offered**
(checkbox) Substance use programs for veterans (service code: VET)
(checkbox) Substance use programs for lesbian, gay, bisexual, transgender (LGBT) clients (service code: GL)

**Opioid Medication-Assisted Treatment (MAT) offered** (Dropdown)
Buprenorphine (service code: BU)
Methadone (service code: METH)
Naltrexone (service code: NU)*** 

Note: I believe you already implemented the MAT filters but I removed them from the type of care section.  
*** NU = **Naltrexone**, not Nalaxone (this was our mistake before - can you update the label in the underlying code if needed? Same service code, we just had it labeled incorrectly before)

**Comment by allisonnorman** [comment]
Adding high priority label because these updates will complete our initial pass at filtering and once in place, we can start incorporating the integrated content components

**Comment by hursey013** [comment]
@allisonnorman also just to clarify, when I click Veteran's Affairs on the current locator it passes through `VAMC` not `VET` - is `VET` a different filter?

**Comment by hursey013** [comment]
Nevermind, `VAMC` looks like it's tied to actual VA locations, which is different than what I think we're trying to do with `VET`.
