### ISSUE TITLE
Outline text in temporary logo

### ISSUE THREAD

**Issue by hursey013** [18F/samhsa-prototype#160]
May not be a huge deal since it's only temporary, but export the text as outlines rather than referencing the font-face so folks that don't have the font locally still see the logo rendered as expected. Noticed this when browsing on my home machine:

![Screenshot from 2019-07-27 09-55-18](https://user-images.githubusercontent.com/1178494/62069173-ae474e00-b205-11e9-83ec-8d518093de71.png)

**Comment by allisonnorman** [comment]
Closing after chatting with Brian. This would be an optimization for our current prototype only and will be resolved in the new design implementation.
