### ISSUE TITLE
Update icon for "understanding addiction"

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#166]
I think our wires got crossed in Slack and icon that we landed on for "understanding addiction" is slightly different than what Kait and Brooklyn requested. 

What we have now:
![Screen Shot 2019-07-30 at 10 35 32 AM](https://user-images.githubusercontent.com/6900926/62151696-c7a7d300-b2b5-11e9-91f5-23c0453b44f5.png)

@BrooklynHopkins and @k8linmarie would like a variation of this using the brain from the screen shot above + arrow circles from the previous iteration. Circles: 
![Screen Shot 2019-07-30 at 10 34 00 AM](https://user-images.githubusercontent.com/6900926/62151769-ef973680-b2b5-11e9-9bdf-b0fc5833844d.png)

@nickttng - Can you get that icon ready when you're back tomorrow and we can swap it out? Let me know if you have any questions or this is unclear. 

Thanks, and apologies for the confusion!

**Comment by nickttng** [comment]
The new addiction files (SVG, PNG@1x, and PNG@2x) can be found in the Visual/UI > Icons > What to Expect
