### ISSUE TITLE
Link state agency list in info content

### ISSUE THREAD

**Issue by amandacostello** [18F/samhsa-prototype#169]
Is there a good list online of state agency contacts? I remember we had something in a PDF. 

https://github.com/18F/samhsa-prototype/blob/3d5b48e1290666b5231b3cb7d2da3366671cfd68/src/utils/content.js#L938

**Comment by Jkrzy** [comment]
The only SAMHSA source I'm aware of is the existing TL: https://findtreatment.samhsa.gov/locator/stateagencies#.XUCje5NKju0

**Comment by allisonnorman** [comment]
@amandacostello - Did you want to link to that in the info content?
