### ISSUE TITLE
Optimize experience for a user changing location once #173 is implemented

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#175]
We have an open issue to update filters automatically upon any filter change instead of having to click "update providers" (#173). This is implemented on a preview branch: https://cg-efcd7c90-b365-4336-8b87-6174f1975c99.app.cloud.gov/preview/18f/samhsa-prototype/bh-search-onchange/

The effect of this change is that if a user changes the location on the results page, the filter updates the list of results automatically and returns a no results message until a new location is entered. This is expected, because as soon as the location is removed, the results are updated automatically and there are no results for no location. 

To reproduce (using the preview link above):
1. Enter a location and click 'find treatment'
2. On the results page, click on the location box and you will see the no results message
3. Upon entering another location, results will be refreshed

@hursey013 and I brainstormed some options but would love to understand what the ideal experience should be from a UX perspective.

**Comment by bpdesigns** [comment]
@allisonnorman For the scope of this feature, this is great. I think that the UI goes from results > no results > updated results is enough of an indicator of the change that happens.

**Comment by allisonnorman** [comment]
I talked to @BrooklynHopkins about this one and she's fine with the behavior as it is for now too. We can observe how people respond to this and optimize as needed.
