### ISSUE TITLE
Study 4 user research - ongoing

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#179]
- Outreach
- Recruitment
- Interviews
- Synthesis

**Comment by bpdesigns** [comment]
Research [Spreadsheet](https://docs.google.com/spreadsheets/d/1tVZy8VFOTMAW4ZPEWIKihgzrfqRqk7QrP2JMbI67fDc/edit#gid=1773725667) and [Study 4 folder](https://drive.google.com/drive/folders/1-QahEESg0iL4iIzKm_4HcZwTzO1AlBDD?usp=sharing) (access limited to internal team)

**Comment by bpdesigns** [comment]
## Study results 
### Synthesis
- study 4 synthesis [mural] (access limited to internal team)(https://app.mural.co/t/gsa6/m/gsa6/1564420042957/d3c3ca63ac07253c77282f094cccd486ddada88f)
- study 3 synthesis [mural] (access limited to internal team)(https://app.mural.co/t/gsa6/m/gsa6/1562098885936/0a1981912d5b9f5af9d734896459062e366767ce) 
- [feedback] (access limited to internal team)(https://docs.google.com/spreadsheets/d/1hsA_qN9QUsDfeFEvRaU85fvDNxVUAUH_152byLdxX7A/edit#gid=1004881069) from visitors to SAMHSA's treatment locator websites and the prototype site 
### Findings 
- findings [deck]( https://docs.google.com/presentation/d/1URb9lZJHaS2KO-mwyX9viW-RViU6PYTa9Gsbz8BtgMk/edit#slide=id.g5e5cdb2316_2_137) (access limited to internal team)
