### ISSUE TITLE
Promote other crisis services in Helpline banner

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#207]
User story:
_As a user in crisis visiting the site, I want to be able to reach out to a crisis service if I need urgent help._

Today, we have the Helpline # displayed prominently on the top of the page. In actuality, Helpline is a referral service that can only help people find facilities, not offer support for those in crisis.

We should explore ways of promoting other support lines, such as the Suicide Prevention Lifeline and 911 for users that are in an emergency.

Some ideas:
- Create a modal building off of the Helpline section in the top navigation today
- Integrated content

**Comment by austinhernandez** [comment]
Add this info to the footer — related to #288 @allisonnorman 

![image](https://user-images.githubusercontent.com/23194720/64286889-51d5fd80-cf2c-11e9-94ad-27906629acce.png)

**Comment by allisonnorman** [comment]
@amandacostello - Do you have any suggestions on the wording for this? Brooklyn and I were thinking something like: "If you are suicidal, call the Suicide Prevention Lifeline (hyperlinked) at 1-800-273-8255 | For emergencies, dial 911." (or vice versa)

**Comment by amandacostello** [comment]
Updated banner text for footer banner: 
If you are feeling suicidal, call the Suicide Prevention Lifeline (hyperlinked) at 1-800-273-8255 | In emergencies, dial 911."

**Comment by hursey013** [comment]
Added
