### ISSUE TITLE
Improve integrated content UX

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#218]
**UPDATE FOR MVP**: 

- [x] Tooltips at filter category level on results page (payment options, as opposed to each option)) - @amandacostello to share tooltip content for each section
- [x] Payment tooltip on details page (not on design, but we can reuse same wording for results page tooltip if @amandacostello confirms)
- [x] Add an "i" icon to "before you call" banner"
- [ ] Smaller cards on details page (transportation is or is not available, and insurance coverage  box) - See design for details page
- [x] @amandacostello - You said you wanted to make changes to the "before you visit" section on the results page. We're not sure if this should be collapsed by default or not. Once you determine the changes that need to be made, can we align on whether this should be collapsed by default?
- [x] (Maybe, depending on above) Collapse "before you go" section on results page by default
______________

Currently, we have links throughout the site that direct people to info content to find out more if they're unfamiliar with the task at hand. 

For example: linking to treatment options near the drop down for type of care ('not sure?'), "before you call" link on the facility cards and details pages, etc. 

Right now, we direct people off of the search page which isn't ideal. We think this could be improved in a way that doesn't disrupt the person's search.

Some ideas: 
- Tooltip
- Modal
- What else?

**Comment by austinhernandez** [comment]
## Tooltips

### Mobile tooltip:

![Tooltip - mobile](https://user-images.githubusercontent.com/23194720/64040387-e73b5100-cb2a-11e9-8c90-ab97004ad773.png)

Interaction pattern:
[Similar to the bottom pop up in mobile view on this page.](https://www.zocdoc.com/doctor/hari-polavarapu-md-7897?LocIdent=97738&dr_specialty=153&insuranceCarrier=324&insurancePlan=2778&isNewPatient=true&reason_visit=75
)


### Desktop tooltip:

![Results page tooltip](https://user-images.githubusercontent.com/23194720/64043068-63d12e00-cb31-11e9-9dba-03547a6154ec.png)

Interaction pattern:
I'm thinking this is more of a click than hover situation because we should link to the "What to Expect page for the lonnnngggggg explanation. Open to suggestions on this, though.

**Comment by bpdesigns** [comment]
@allisonnorman @austinhernandez was this determined to be out of scope? I think the tooltips that @austinhernandez designed look great.

**Comment by allisonnorman** [comment]
@bpdesigns - It's in scope. We'll be doing tooltips on the category filter level though instead of on the filter level (not because of design but because content would be somewhat redundant).

**Comment by amandacostello** [comment]
Tooltip text for filter titles

TREATMENT TYPE
There are many types of and places that treat substance use disorder; your recovery may include more than one of these. [See more details about these types of treatment](https://findtreatmentbeta.18f.gov/content/treatment-options/types-of-treatment)

PAYMENT OPTIONS
Understanding paying for treatment can be hard and confusing, but don’t let this stop you from finding help.
- [If you have insurance](https://findtreatmentbeta.18f.gov/content/paying-for-treatment/if-you-have-insurance)
- [If you don’t have insurance](https://findtreatmentbeta.18f.gov/content/paying-for-treatment/if-you-dont-have-insurance)

MEDICATION-ASSISTED TREATMENT (MAT)
Medication-assisted treatment (MAT) is often a successful treatment for people who are addicted to opioids or alcohol. This treatment uses FDA-approved medication together with counseling and behavioral therapies.
[Learn more about the medications approved for MAT] (https://findtreatmentbeta.18f.gov/content/treatment-options/medications-used-in-treatment) and how they can help with recovery.


BEFORE YOU VISIT (starting state collapsed, info-circle icon or other thing to expand box)
- Call a facility before you visit to make sure they have the services you need. [What to expect when you call. ](https://findtreatmentbeta.18f.gov/content/treatment-options/calling-a-facility)
- Not sure what you need? Learn more about different types of treatment. 


outside of/below box but before search results
_All facilities are licensed by their states, and provide assessments._

**Comment by amandacostello** [comment]
Checked off my bits at the top of this, ready for a ton of eyes! @allisonnorman @hursey013 @bpdesigns @austinhernandez

**Comment by amandacostello** [comment]
In case we want to do-away with the tooltips, here's another version, links to live under the headers.

TREATMENT TYPE
[Details about treatment types](https://findtreatmentbeta.18f.gov/content/treatment-options/types-of-treatment)

PAYMENT OPTIONS
[Not sure how to pay?](https://findtreatmentbeta.18f.gov/content/paying-for-treatment/understanding-the-cost-of-treatment)

MEDICATION-ASSISTED TREATMENT (MAT)
[Details about FDA-approved medications] (https://findtreatmentbeta.18f.gov/content/treatment-options/medications-used-in-treatment)

BEFORE YOU VISIT (starting state open, info-circle icon or other thing to expand box)

- Call a facility before you visit to make sure they have the services you need. [What to expect when you call.](https://findtreatmentbeta.18f.gov/content/treatment-options/calling-a-facility)
- Not sure what you need? [Learn more about different types of treatment.](https://findtreatmentbeta.18f.gov/content/treatment-options/types-of-treatment)

outside of/below box but before search results
_All facilities are licensed by their states, and provide assessments._

**Comment by hursey013** [comment]
Just to echo https://gsa-tts.slack.com/archives/CEGB4TU4S/p1569353422093500 - supporting links within tooltips is going to be difficult from an accessibility and mobile touch perspective. I'm not saying it's impossible, but in terms of our MVP I think we should consider alternatives or text only tooltips. Also would love to get @iamjolly's take on this!

**Comment by tbaxter-18f** [comment]
I like this take a lot better. In design phase, maybe a ? icon might help? 

Regardless of design, I think this is a better, more useful, solution for everyone than hiding the content behind a tooltip.

**Comment by iamjolly** [comment]
Simpler will be better (no links or other functionality in them) for accessibility of the tooltips as MVP material.

**Comment by amandacostello** [comment]
Moved the text details into #365 , this is ready to close @hursey013
