### ISSUE TITLE
Interacting with filters when location is not set is confusing

### ISSUE THREAD

**Issue by hursey013** [18F/samhsa-prototype#232]
If there is no `Location` set, any interaction with the form does not produce any noticeable changes. This can be especially confusing if you have previously searched used a location and have results displayed, then clear out the location and interact with the filters - the previous results will continue to remain unchanged.

**Comment by bpdesigns** [comment]
A few good ideas suggested by @allisonnorman today which I think are good ux solves for this issue

**context**: when no location is set on the [search results] page

**change**:
- add alert text above the Location filter box in red  "select a location to enable filters' 
- disable filters 
- make the text in each filter gray 

**Revert**: when visitor selects a location

@hursey013 let me know if this is clear. Thanks
