### ISSUE TITLE
Move content into separate pages

### ISSUE THREAD

**Issue by amandacostello** [18F/samhsa-prototype#236]
Each H2/navigation sub-item should be its own page with unique URL. Leave the content from the first item on the landing page.

Example: https://findtreatmentbeta.18f.gov/content/paying-for-treatment

> **Paying for treatment**
> _Learn more about the cost of treatment and payment options._
 
would remain at the top of each page. The landing page would include content from the first section just below it, in this case 

> **Understanding the cost of treatment**

Please ping or ask more questions here about other things you want to know for the engineering-actually-doing-this process!

**Comment by allisonnorman** [comment]
@amandacostello - Can you pull together a meeting with Brian, Austin, Ben to talk through this more?

**Comment by allisonnorman** [comment]
Closing as I've consolidated the info content asks into one issue: #223
