### ISSUE TITLE
Update filter for "types of care"

### ISSUE THREAD

**Issue by amandacostello** [18F/samhsa-prototype#238]
The secondary filter **"Type of Care"** should be renamed **"Types of treatment"**, with a "Not sure?" inline link next to it that goes to the types of treatment section: https://findtreatmentbeta.18f.gov/content/treatment-options#types-of-treatment

**Comment by allisonnorman** [comment]
@amandacostello - There's a singular and plural version of this label. I'm wondering if "type of treatment" make sense for the label and then the plural can be used in the default "all types of treatment"? What do you think?

**Comment by amandacostello** [comment]
Ahhh yes! The label should be singular (since you can only pick one) and the header can stay the same on the Treatment Options page. Good catch, yo! :)

**Comment by amandacostello** [comment]
Also thanks for re-opening because I just blithely clicked on whatever button I wanted. :D
