### ISSUE TITLE
Add handling for Places API errors

### ISSUE THREAD

**Issue by Jkrzy** [18F/samhsa-prototype#243]
When we're unable to retrieve results from the Places API we should render an error page and direct visitors to call the helpline for assistance. We handled `ZERO_RESULTS` responses in  https://github.com/18F/samhsa-prototype/issues/101. 

https://developers.google.com/maps/documentation/javascript/places#place_details_responses

Other non-`OK` responses should be direct the visitor to call the helpline as the locator is temporarily out of service.

Let's also explore logging and alerting on these errors by leveraging google analytics.

**Comment by hursey013** [comment]
@Jkrzy do envision handling these errors in a similar way as `ZERO_RESULTS` - displaying a red inline error under the input, or something else?

**Comment by Jkrzy** [comment]
A message similar to `Error.js` would be appropriate. We're unable to perform searches if this endpoint becomes available.
