### ISSUE TITLE
Prototype - go live prep 

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#244]
- [x] Clear out Google Analytics - @Jkrzy will do this morning of 8/21
- [x] Accessibility scan/remediation
- [x] Coordinate with ET to launch beta banner - @BrooklynHopkins sent email to Nichele on 8/20, asking for launch by COB 8/21
- [x] Browser compatibility
- [x] Update README

**Comment by Jkrzy** [comment]
Submitted #245 to move to a new GA property.
