### ISSUE TITLE
Add GitHub link to prototype

### ISSUE THREAD

**Issue by hursey013** [18F/samhsa-prototype#254]
To support developing in the open, and to open up technical feedback/contributions.

**Comment by davemcorwin** [comment]
@hursey013 Any idea where on the page we want this?

**Comment by hursey013** [comment]
Definitely in the footer. Probably just added to the column with `Home`, `Privacy Policy`, etc. Maybe sneak a https://fontawesome.com/icons/github?style=brands in there if there's room 😉
