### ISSUE TITLE
"More Filters" clears selections when collapsed

### ISSUE THREAD

**Issue by Jkrzy** [18F/samhsa-prototype#265]
If I select a criteria under `More Filters` and then collapse that section my selections are cleared and the search results are refreshed.

I _think_ the expected behavior would be to leave those filters active and not refresh the search results until a user has actively modified the set of filters/selections.

Thoughts @hursey013 , @bpdesigns?

**Comment by bpdesigns** [comment]
Yes. That makes sense to me.
