### ISSUE TITLE
Implement design for desktop home page and mobile home page

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#268]
Visual design assets (sketch file with final designs): https://drive.google.com/open?id=1Z2oYUfV_ETZP5rTFgN3EQ0MLldVMGqPU

**Comment by allisonnorman** [comment]
Brian/Allison sync before vacation

Preview branch: https://cg-efcd7c90-b365-4336-8b87-6174f1975c99.app.cloud.gov/preview/18f/samhsa-prototype/bh-visual-design/

**Home**
- Most finished of the pages, but still in progress
- Need mobile feedback
- Still working on:
- Hover states
- We will need to update the SVG with the domain name
- Helpline on home doesn’t show on mobile
- Do we need to update the footer? 
- Filter interaction (needs help with us on this)

**Search/results page:**
- Visually 80-90% there for desktop
- Will need to tweak some of the styling for mobile
- Code wise, a bit more to do to optimize the code
- Need visual/feature audit from team. 

On Brian’s radar already for results page:
- Show distance on facility cards
- Maybe: update list of services that show up on the card for payment and type of care (for example: remove state-financed health)
- Update header box styling (use blue styles)
- What else is missing? What else is off?
- Print button
- Questions
- Underlined filter names on card?

**Details page**
- Much of the visual design has been applied, but still in progress
- Will need to do the text implementation (based on Amanda’s feedback) still but this is the first pass
- Print button

Other
- Will need to add beta banner before we go live

**Next up for Brian when he gets back:**
- Optimize mobile
- Implement changes on details page
- Info content
- Sit with Austin at onsite to get design input

**From our team, he needs:**
- Info content pages/designs fleshed out and ready for handoff
- Footer changes, if applicable
- Filter interactions recommendations
- Schedule in person design bash with Austin at onsite
- Bug bash / try to break the site
- Everyone should audit the site and see if we have lost anything as we’ve transitioned to the new design
- Review print styles

**Comment by hursey013** [comment]
@allisonnorman Closing as these tasks are complete or tracked elsewhere
