### ISSUE TITLE
Add transitional housing as a type of treatment

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#279]
We have received a few comments on the feedback form to add transitional housing, or halfway houses to the list of filters. 

- "My only feedback is that you should add halfway houses as a service setting."
- "Wow, what a pleasant surprise from someone who uses this information daily since I work for the National Help Line.....However, I did notice there are no options for 'Transitional Living'"

This change will include:
- [x] Making the change to add the filter - @allisonnorman 
- [x] Adding a blurb in the type of treatment content about transitional housing - FYI @amandacostello 

Quick question before we begin: @BrooklynHopkins - I'm assuming that "transitional housing" is the right term we should use for this filter (as opposed to halfway house or sober home?) What do you think?

**Comment by allisonnorman** [comment]
The new filter with descriptor text is on the new branch.

@amandacostello - What should we update on the type of treatment info content to support the new filter?

**Comment by amandacostello** [comment]
**Transitional Housing**
_A temporary space to stay while transitioning from an intensive treatment setting. Sometimes called a halfway house or sober living facility._

As part of the path to independent living, these facilities support people in recovery with temporary places to live. They may also have support programs around employment and education, or case managers to help residents succeed during and after their stay.

**Comment by amandacostello** [comment]
Blurb is here @allisonnorman - ready for review and upload!

**Comment by allisonnorman** [comment]
Great! I may save this to do with @BrooklynHopkins next week in person!

**Comment by allisonnorman** [comment]
Resolved in #294
