### ISSUE TITLE
Add link to google maps/directions from map interface

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#28]
We want to support people engaging with the map in a more detailed way outside of the locator by introducing a link to Google maps on the locator map interface on the results page and facility details pages.

- Facility details page - pass the location of the facility so that when a visitor clicks on it, they see the location populated in google maps
- Results page - would it be possible to have the same map with pins populated within google? Or what would this look like?

**Comment by Jkrzy** [comment]
Possible, should be able to leverage available data to generate a URL to generate a map/pin for each facility. Ideally we'd have `place_id` for each but I don't believe thats available at the moment. 

https://developers.google.com/maps/documentation/urls/guide#search-action

This approach could generate interesting results if the facility data doesn't match up with Google's location/place data.
