### ISSUE TITLE
Search for Washington, IN returns Washington state results

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#280]
From our feedback form: 
_In both versions, please work on the search engine -- example, try & search for Washington, Indiana -- you only bring up the STATE of Washington, not Indiana."_

I can reproduce this by searching for Washington, IN and expanding to a 50 mile radius. If I search using a zip code for that are 47501, relevant results are returned. I'm assuming this is an issues with the Google API and nothing we can do to change it but logging it just in case.

**Comment by hursey013** [comment]
Fixed with https://github.com/18F/samhsa-prototype/commit/519facaea2b22743d56bc58bf40c1e2e77bbda9c
