### ISSUE TITLE
Update footer to align with new design

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#288]
TLDR for Brian: 
- (From Austin): "It just needs to inherit the font Public Sans and the color can stay #2C3747".
- There's a related issue (#207) to add a banner below the footer to promote other crisis services. 

Brian mentioned that the footer we are using is still the original one he threw together. @austinhernandez - Do you have any recommendations to change based on the the new colors and typefaces?

**Comment by austinhernandez** [comment]
No it's good! It just needs to inherit the font Public Sans and the color can stay `#2C3747` 

I am unsure on the content of this section, however. Is this where emergency numbers could live? Or secondary navigation?

**Comment by allisonnorman** [comment]
Thanks, Austin! 

Interesting idea around putting some of the emergency #s in there. That section was largely a way of tying people back to some of the existing resources that are commonly accessed from the current TL. As for emergency #s -  I think we _could_, if even for MVP to see hover usage metrics in Crazy Egg. We can see people are making their way to the footer, but I'm not sure in an emergency someone would, so this could be a step in understanding more. Until we know whether we need to message "call 911" more prominently, I think this could work.

**Comment by austinhernandez** [comment]
Add this info to the footer — related to #207 @allisonnorman 

![image](https://user-images.githubusercontent.com/23194720/64286889-51d5fd80-cf2c-11e9-94ad-27906629acce.png)

**Comment by bpdesigns** [comment]
LGTM

**Comment by hursey013** [comment]
Banner has been added.
