### ISSUE TITLE
Plan out and coordinate with ET as to how they will link to FindTreatment.gov during launch

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#289]

**Comment by allisonnorman** [comment]
@amandacostello - Can you put the language you shared with @BrooklynHopkins here so we can track as we get closer to launch?

**Comment by amandacostello** [comment]
@allisonnorman Here's the language I gave to Brooklyn last week:

We have a new site for finding addiction and substance use disorder treatment: https://findtreatment.gov/
