### ISSUE TITLE
Remove "all types of treatment" from MAT dropdown

### ISSUE THREAD

**Issue by bpdesigns** [18F/samhsa-prototype#293]
## Issue: 
Feedback on the beta site shows possible confusion with the MAT dropdown list. I think this might be a search blocker.

> if you expand the filters you have to choose a MAT. This may not be appropriate for all persons seeking treatment. I think the drop down should also have an N/A option.

<img width="293" alt="Screen Shot 2019-09-06 at 8 25 04 AM" src="https://user-images.githubusercontent.com/15329140/64427783-ffa5f100-d07f-11e9-9f4c-de045374700b.png">
**UPDATE FOR MVP**: Remove "all types of treatment" option from MAT section

## Suggestion:
Add an N/A button
- this gives the visitor the option to do an action that gives them more confidence to complete their search
- Because of the limitations of the OR logic with the filters I would have the filtering mechanism show the same results for All Treatments

**Comment by bpdesigns** [comment]
would love others thoughts on this.

**Comment by allisonnorman** [comment]
@bpdesigns - Do you think this still applies with the new design?

Given that the back end doesn't support "xyz minus MAT" (and not logic), I think that an N/A option could be misleading. Happy to chat through this more if this makes sense.

**Comment by bpdesigns** [comment]
@allisonnorman I think so. Lets chat about it later today.

**Comment by allisonnorman** [comment]
We discussed and decided to remove the "all types of treatment" option for the MAT section
