### ISSUE TITLE
Add location validation / specific error messages when no location is input

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#30]
When I don't enter a location in the location search box, or if I enter $$$$$$, I get an "Oops - no result" message. 

Per a convo with @hursey013 and @Jkrzy, we should provide more specific error messaging. 

Something like "It looks like you didn't provide a valid city or zip code" but cc'ing @amandacostello for content input.

**Comment by hursey013** [comment]
This has been resolved - the submit button is disabled until a valid location is selected.
