### ISSUE TITLE
Empty state and error state content

### ISSUE THREAD

**Issue by amandacostello** [18F/samhsa-prototype#301]
Empty state content (when no location was entered into search)

# Searching for treatment options

Start by entering your ZIP code. Locations within 25 miles will be shown first, and you can change the distance to show more or fewer locations.

Use the search filters to find locations that match specific needs, like the type of treatment offered, groups served, or medication availability. 

**If you need help searching, SAMHSA's national helpline is available 24/7 and can help with treatment referrals and information. Call 1-800-662-HELP (4357) to speak to someone.**

Error state content (when the search returned no locations)

# We couldn't find any providers near you.

Widen your search by applying fewer filters, like only your ZIP code and payment option, or expanding your search distance.

**If you need help searching, SAMHSA's national helpline is available 24/7 and can help with treatment referrals and information. Call 1-800-662-HELP (4357) to speak to someone.**

**Comment by bpdesigns** [comment]
@allisonnorman seems ready to close. 

**We couldn't find any providers near you.** copy looks a little different (see below)  but the **Searching for treatment options** is updated. 

**We couldn't find any providers near you.**
- Try expanding your search by applying fewer filters, like only your ZIP code and payment option, or expanding your search distance.
-If you need assistance, SAMHSA's national helpline is available 24/7 and can assist you with treatment referrals and information. Call 1-800-662-HELP (4357) to speak to someone.
