### ISSUE TITLE
Search results feedback

### ISSUE THREAD

**Issue by austinhernandez** [18F/samhsa-prototype#305]
<img width="617" alt="Screen Shot 2019-09-12 at 10 42 14 AM" src="https://user-images.githubusercontent.com/23194720/64795068-7db83b00-d54b-11e9-826f-9dbce94c4b2f.png">

- [ ] truncate the max number of "types of care"
   - co-work with @amandacostello to decide the max number of terms. which ones should be prioritized?
- [ ] a lot of these are changing based on the latest mocks. sorry :( 

New:
![image](https://user-images.githubusercontent.com/23194720/64796654-059f4480-d54e-11e9-8929-20f2dce1864d.png)

**Comment by bpdesigns** [comment]
@allisonnorman I think this issue is ready to close.
