### ISSUE TITLE
Photos on homepage render issue in Win10 Edge

### ISSUE THREAD

**Issue by iamjolly** [18F/samhsa-prototype#313]
Screenshot:
![samhsa-home-ms-edge-win10](https://user-images.githubusercontent.com/1093423/64820464-ac470d80-d56d-11e9-979f-a568d727af22.png)

Not an accessibility issue, but it looks like a mistake/not rendering as intended on Win10 in Edge.

**Comment by hursey013** [comment]
@iamjolly do you have the ability to re-check this? The photos have sense been switched to JPGs which I think might have resolve the issue.

**Comment by iamjolly** [comment]
Checking nw @hursey013... will update here in a bit.

**Comment by hursey013** [comment]
I was able to get Edge running. It's wasn't fixed but I figured out this issue, going to open a PR.

**Comment by iamjolly** [comment]
Looks right on Win10/Edge now for me!
![Screen Shot 2019-09-26 at 3 06 10 PM](https://user-images.githubusercontent.com/1093423/65725217-58f5b480-e06f-11e9-8f1f-c37d468116e3.png)
