### ISSUE TITLE
homepage feedback part 2

### ISSUE THREAD

**Issue by austinhernandez** [18F/samhsa-prototype#323]
it looks like some of the changes reverted since #304 ? here is my feedback

<img width="903" alt="Screen Shot 2019-09-16 at 3 57 17 PM" src="https://user-images.githubusercontent.com/23194720/65068283-56e87300-d956-11e9-94bb-3633564664f2.png">

- [ ] round the corners on helpline on the right side
- [ ] decrease line height to: 2.4rem
- [ ] font-family: public sans buttons and semi bold

**Comment by hursey013** [comment]
Implemented in preview branch
