### ISSUE TITLE
Mobile navigation. "Search for treatment" link path

### ISSUE THREAD

**Issue by bpdesigns** [18F/samhsa-prototype#325]
## Current state. 

1. From any page. Select the hamburger menu in upper right. 
2. If no location was previously searched: go to [this page](https://cg-efcd7c90-b365-4336-8b87-6174f1975c99.app.cloud.gov/preview/18f/samhsa-prototype/bh-visual-design/results)
<img width="498" alt="Screen Shot 2019-09-17 at 5 36 22 PM" src="https://user-images.githubusercontent.com/15329140/65083194-dfc2d700-d975-11e9-9ec8-5f9446130bd9.png">

## Suggested state. 
1. From any page. Select the hamburger menu in upper right.
2. [navigation] If no location was previously searched: go to the filters page with an empty location search.

**Comment by bpdesigns** [comment]
## Possible extension on this
- not ideal solution but better than the current state
- Place the "show results" button below the "distance" button. 
<img width="350" alt="Screen Shot 2019-09-17 at 6 10 10 PM" src="https://user-images.githubusercontent.com/15329140/65084159-65478680-d978-11e9-9b34-0d4eee24c9cf.png">

## I'm of two minds on this
- keep this placement of the "show results" button after a location is entered. 
- OR remove completely the "show # results" from the top of the page. This means it would be only at the bottom of the page. 
<img width="483" alt="Screen Shot 2019-09-17 at 6 34 13 PM" src="https://user-images.githubusercontent.com/15329140/65084633-c6238e80-d979-11e9-8afb-29a1eb79bd68.png">

**Comment by davemcorwin** [comment]
@allisonnorman  @bpdesigns I don't understand the desired state.

Currently the hamburger opens a menu where the user can choose `Home`, `Search`, etc... (see below). How does the suggestion change this behavior?


![Screen Shot 2019-09-27 at 8 59 25 AM](https://user-images.githubusercontent.com/6662371/65783732-4201a180-e105-11e9-8a35-a3a8707d5ecb.png)

**Comment by bpdesigns** [comment]
my suggestion is that instead of going to this page on mobile from the "search for treatment" button 
<img width="498" alt="Screen Shot 2019-09-17 at 5 36 22 PM" src="https://user-images.githubusercontent.com/15329140/65784497-2f489600-e120-11e9-9735-398b3ca4dd9a.png">

go to this page
<img width="500" alt="Screen Shot 2019-09-17 at 5 37 12 PM" src="https://user-images.githubusercontent.com/15329140/65784518-3a9bc180-e120-11e9-8917-7b16347760b6.png">

**Comment by bpdesigns** [comment]
I'll say I think it would be ideal to add the "searching for treatment options" note above the "filter" page content.
