### ISSUE TITLE
Mobile filters page - better signaling when the "show results" button is disabled

### ISSUE THREAD

**Issue by bpdesigns** [18F/samhsa-prototype#332]
## Problem
Background - on the Mobile filters page when there is no location entered it can be unclear that the "show results" button is disabled (at the top and bottom of the page). 

## Suggestion
Better signaling that the "show results" button is disabled (at the top and bottom of the page).
Maybe an onclick state that: 
- changes the color of the button to be more clearly grayed out
- maybe error text above the button that says "please enter a city or zipcode" like we have on the homepage.

**Comment by davemcorwin** [comment]
@bpdesigns For now, I think increasing the opacity of the disabled submit button addresses the first concern. Regarding the error message, it is displayed under the same conditions as on desktop, that is, when invalid data is submitted, but NOT when the no data is submitted. As discussed in #308 , we may want to handle that separately. Moving the error message text is also included in #308.

Updating the opacity will look like:

### Not disabled:
![Screen Shot 2019-09-27 at 8 49 36 AM](https://user-images.githubusercontent.com/6662371/65783027-c0f5da80-e103-11e9-862c-a4d91e3e9ead.png)

### Old:
![Screen Shot 2019-09-27 at 8 48 13 AM](https://user-images.githubusercontent.com/6662371/65782944-9a37a400-e103-11e9-8b52-9df4a9501ce7.png)

### New:
![Screen Shot 2019-09-27 at 8 47 56 AM](https://user-images.githubusercontent.com/6662371/65782947-9c016780-e103-11e9-86f1-17350670fc22.png)


LMK is this looks good. @bpdesigns @austinhernandez

**Comment by bpdesigns** [comment]
LGTM

**Comment by bpdesigns** [comment]
NVM #308 covers this
