### ISSUE TITLE
Visible focus on facility result heading is hard to perceive

### ISSUE THREAD

**Issue by iamjolly** [18F/samhsa-prototype#340]
### Problem Description
The focus outline for the site uses browser defaults. On Chrome and Safari, the default outline is blue, and when it is set against a blue background, it becomes very difficult to perceive, especially for those with visual disabilities. 

![samhsa-visible-focus-facility-result](https://user-images.githubusercontent.com/1093423/65361691-be562b00-dbc1-11e9-932a-98cf91624d0f.png)

### Recommended Solution
Consider adding an updated focus outline for the facility results headings to override the browser defaults to ensure a more visible outline against the blue background.

**Comment by allisonnorman** [comment]
@austinhernandez - Do you have thoughts on a color that could be broadly applied?
