### ISSUE TITLE
`node_modules` folder is served

### ISSUE THREAD

**Issue by davemcorwin** [18F/samhsa-prototype#341]
The entire `node_modules` folder is being served which is not desirable as it exposes application dependencies and slows deployments since everything is copied to S3.

For Jekyll sites, this can be (explicitly excluded)[https://federalist.18f.gov/documentation/node-on-federalist/], I'm not sure of the appropriate way to do it for generic `node` sites.

![Screen Shot 2019-09-20 at 3 38 26 PM](https://user-images.githubusercontent.com/6662371/65362620-f60ea400-dbbc-11e9-9002-f4037861ffb3.png)

**Comment by adunkman** [comment]
This isn’t the most straightforward UI, but folders which show up in orange in the Sources panel are [from a source map](https://developers.google.com/web/tools/chrome-devtools/javascript/source-maps) — not sure if those files are actually served (or if they’re just being shown in DevTools via source map to aid in debugging).

Definitely doesn’t help with deployment time though if the files are copied regardless.

**Comment by hursey013** [comment]
Can't speak to why `node_modules` appears in the dev tools, but just validated it's only the contents of the `/build` directory being uploaded and served through Federalist. If there is additional action to take to remove the source maps, let me know.

**Comment by davemcorwin** [comment]
ahhh, cool, thats interesting about the dev tools, sorry for the noise all.
