### ISSUE TITLE
Add "reset filters" back in

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#349]
I think we list this functionality as the design has been implemented. 

Here was the original PR (I believe) implementing this originally: #27

**Comment by davemcorwin** [comment]
@allisonnorman The UI looks quite a bit different than it did when this feature was initially implemented, is there in existing design that includes this feature or is this something on which we need some feedback from design / @bpdesigns ?

**Comment by davemcorwin** [comment]
To clarify, this feature appears to exist on mobile (see screenshot) but not on desktop.

![Screen Shot 2019-09-23 at 2 52 45 PM](https://user-images.githubusercontent.com/6662371/65465711-d2906700-de11-11e9-9630-b815dba1059f.png)

**Comment by bpdesigns** [comment]
yes.

**Comment by allisonnorman** [comment]
Good point, @davemcorwin! I don't think it's reflected in the design which is why it probably got left off as the design was implemented. @austinhernandez - Do you have a recommendation on where the clear filters could live on desktop?  Maybe somewhere under "Refine search results"?

**Comment by davemcorwin** [comment]
hehehe, my naive implementation looks like:

![Screen Shot 2019-09-23 at 5 42 38 PM](https://user-images.githubusercontent.com/6662371/65472693-936e1000-de29-11e9-8241-2b6da3a08a77.png)

**Comment by hursey013** [comment]
Yeah I think this is a bit more involved, the new design changes the `Clear all` interaction into a bigger system of toggling specific filters on and off:
<img width="653" alt="Screen Shot 2019-09-24 at 10 58 44 AM" src="https://user-images.githubusercontent.com/1178494/65523578-7897ac00-deba-11e9-9166-c1dce503a32d.png">
We need to decide if this issue it to create an interim solution like @davemcorwin has proposed above, or are we saying the complete filtering toggling interaction should be present in the mvp? Thoughts @allisonnorman?

**Comment by allisonnorman** [comment]
Based on our timeline, I think we should stick with the interim solution for MVP. I will find the issue for the advanced filters and move to post-MVP.
