### ISSUE TITLE
Pre-launch Github housekeeping

### ISSUE THREAD

**Issue by hursey013** [18F/samhsa-prototype#350]
Open questions:

- Should we rename this repo in order to remove `prototype`?
- Does this belong in the 18F Github org, or should we transition/create a SAMHSA org?

**Comment by allisonnorman** [comment]
@hursey013 - What do we typically do? What did you do on the PRA project?

I am inclined to remove the word 'prototype.' As for transitioning to a new org within Github, I am not sure the implications of this or it staying in 18F (would there be access limitations for new people joining if it stays in 18F). Added a high-priority label so we don't lose track of this and can talk about it with Brooklyn.

**Comment by allisonnorman** [comment]
@hursey013 - Talked to Brooklyn and have some answers:
- We should keep the name samhsa-prototype
- Let's keep in the 18F org for now. I've added a task in our transition planning issue (#275) to revisit as we get closer to handoff. 

Closing this for now as we're tracking elsewhere.
