### ISSUE TITLE
reorder the pages under "treatment options"

### ISSUE THREAD

**Issue by bpdesigns** [18F/samhsa-prototype#355]
## Current order:
- Calling a facility
- What happens next?
- Who provides care?
- Types of treatment
- Medications used in treatment

## UX test feedback

- [clicks on “treatment options” in top nav. Takes her to the “calling a facility” page]
- Confused about “calling a facility”...is this through you guys? These are the questions I’d be asking when calling facilities.
- I don’t understand. Is this giving someone looking for treatment what to do?
- Consider title of pages. What info do you think when you click on “treatment options”. What do you think might have been expected?
- Maybe different types of facilities there are.

## Suggested reorder 
- Types of treatment
- Medications used in treatment
- Calling a facility
- What happens next?
- Who provides care?

**Comment by bpdesigns** [comment]
@amandacostello thoughts on this?

**Comment by allisonnorman** [comment]
I think this makes a lot of sense. Once you take a look @amandacostello, I'm happy to make the changes or pair. It's pretty straight forward but something we should probably test locally as moving around the bracketed section can be error prone.

**Comment by amandacostello** [comment]
Absolutely cool with moving these around, this order makes a ton of sense. 👍
