### ISSUE TITLE
Revisit footer

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#396]
- [X] Remove home? (Replace with required About page) - in progress
- [x] Reorganize?
- [X] Remove 4th column with SAMHSA address (that information is easily findable on the SAMHSA homepage which we link to in the first column). 
- [x] Adjust column spacing - https://gsa-tts.slack.com/archives/CGBQQ8KFD/p1569958284112600

Do we have all of the links necessary? https://digital.gov/resources/required-web-content-and-links 
- [X] Missing About Page (https://www.samhsa.gov/about-us) - in progress

**Comment by bpdesigns** [comment]
## Suggestion for reorganizing content in the footer
- Remove SAMHSA's Mission statement 
- Replace that content with a statement about where the data come from.
