### ISSUE TITLE
Functional testing for the new Eagle Tech endpoint

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#398]
Preview link: https://cg-efcd7c90-b365-4336-8b87-6174f1975c99.app.cloud.gov/preview/18f/samhsa-prototype/bh-aws-endpoint/

Doc to track issues: https://docs.google.com/document/d/1zAl8U7vXiMsPP4ikdAob7DNVIMJCdHVvlqJCY5JE_H4/edit

**Comment by allisonnorman** [comment]
- [ ] Seeing slightly different distance returned for some facilities (For 95126, I see Santa Clara Dept of Alc. Distance in prod  0.44, distance in staging: 0.43) (Horizon Services Inc South - 1.27 mi in staging, 1.28 in prod)
- [ ] Seeing similar # of results returned (54 in staging vs 55 in prod), with a different order

**Comment by Jkrzy** [comment]
Super-ceded by #445
