### ISSUE TITLE
Mobile "filters" button should send visitors to the top of the results page

### ISSUE THREAD

**Issue by bpdesigns** [18F/samhsa-prototype#415]
## Current State
On the mobile "filters" page, if you are not at  the top of the page when you click either of the  "filters" button, you will not be sent to top of the "results" page. You will be taken somewhere lower in the page depending upon your current screen view of the page when you click on the  "filters" button at the top or bottom of the page. 

## Desired State
Clicking on the "filters" button should send visitors to the top of the "results" page

**Comment by allisonnorman** [comment]
I was able to reproduce this once but when I tried to screen capture, I couldn't. @bpdesigns - if you're easily able to, can you walk me through it or screen capture? Thank you!

**Comment by bpdesigns** [comment]
1. On mobile. From the filters page scroll down a little on the screen until the first "filters" button is at the top of page.
2. once you select that button it should return you to the results page partially down the page.
- If you click the filters button from the top of the page it won't show the change because the screen is at the top. I think its something where it will match however far down the page you are on the filters page with the results page. It might have something to do with the fact that they are the same page on desktop.

**Comment by allisonnorman** [comment]
Got it! Here's a video: https://drive.google.com/open?id=1XjGhefKVTRyyqDYOdyFTgix_4ayOU5AA
