### ISSUE TITLE
Add the "return to top" button on mobile facility pages

### ISSUE THREAD

**Issue by bpdesigns** [18F/samhsa-prototype#417]
## Current state 
The return to top button is missing from the facility pages. 

## Desired state 
The return to top button is on all pages.

**Comment by allisonnorman** [comment]
Back to top has been implemented on all mobile pages. We have an issue open for desktop but moved it to out of scope for MVP (#394) Do you think adding this to desktop is important for MVP launch?

**Comment by bpdesigns** [comment]
@allisonnorman can you confirm that the link is there on the Facility pages? I just double checked and I don't see the link on those pages. 

I don't think the desktop link is important for MVP

**Comment by allisonnorman** [comment]
Good catch. I think it was intended to be on all page. I'll pull this in.
