### ISSUE TITLE
Reordering the top nav 

### ISSUE THREAD

**Issue by bpdesigns** [18F/samhsa-prototype#419]
## Current State
- Search for treatment
- Understanding addiction
- Understanding mental health
- Treatment options
- Paying for treatment

## Problem
The research overwhelming shows that the top things people are interested in for finding treatment are "what do different types of treatment mean?" and "How can I pay for treatment?" Currently, "Treatment options" and "Paying for treatment" are the last links in the list. 

## Suggestion
Reorder the nav to make "Treatment options" and "Paying for treatment" faster to find. 

- Search for treatment
- **Treatment options**
- **Paying for treatment**
- Understanding addiction
- Understanding mental health

**Comment by allisonnorman** [comment]
This one would be an easy change to make technically. Would we need to also shift the rest of the sections as well (bottom of fold content section, sub-sections within the info content section, etc or leave as is? I think they were intentionally aligning with the overarching narrative of the path a person might take but I think that it won't necessarily negatively affect the flow to make changes based on Ben's suggestions. What do you think, @amandacostello?

**Comment by bpdesigns** [comment]
I agree with @allisonnorman that this should also shift the left side nav on the content pages. 

I don't think we need to reorder the content on the homepage. Having addiction and mental health under the "learn more" maps to content about learning about the issue someone might have. At that point the details about searching for facilities is likey secondary.

**Comment by amandacostello** [comment]
I'm down with the changes for the top and left nav, and also cool with leaving the bottom info boxes in the same order. 👍
