### ISSUE TITLE
Reorder autocomplete search to deprioritize state results in favor of cities.

### ISSUE THREAD

**Issue by bpdesigns** [18F/samhsa-prototype#423]
## Current state 
The search button tries to autocomplete to the name of a state first. Further autocomplete suggestions are for cities. 

## Desired state
Autocomplete to have results for cities before those of states. 

## Rationale
- Search by cities give searchers more targeted searches.
- Our search by state focuses outward from the center point of a state, which in some states sends back no results within 25miles of the center of the state

**Comment by hursey013** [comment]
This is controlled by the google places API. The options are:
>google.maps.places.RankBy.PROMINENCE (default). This option sorts results based on their importance. Ranking will favor prominent places within the set radius over nearby places that match but that are less prominent. Prominence can be affected by a place's ranking in Google's index, global popularity, and other factors. When google.maps.places.RankBy.PROMINENCE is specified, the radius parameter is required.

>google.maps.places.RankBy.DISTANCE. This option sorts results in ascending order by their distance from the specified location (required). Note that you cannot specify a custom bounds and/or radius if you specify RankBy.DISTANCE. When you specify RankBy.DISTANCE, one or more of keyword, name, or type is required.

**Comment by bpdesigns** [comment]
Got it. It seems that search by prominence in our context could seem random.
