### ISSUE TITLE
(Still needed?) Test publishing prototype on FindTreatment.gov

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#427]
@hursey013 - What are your thoughts on this? Do you recommend we still do this? The farther out from launch we are, the better and if doing this is one less thing to check off later, I'm all for it.

**Comment by hursey013** [comment]
I think as long as we leave ourselves sufficient time on launch day to double check that routing is working properly (no issues going directly to links) this should no longer be necessary. We have all of the pieces in place and Federalist is already pointing traffic our landing page branch on findtreatment.gov.

**Comment by allisonnorman** [comment]
Thanks! Added a note about that in #344 (launch checklist)
