### ISSUE TITLE
Add error page

### ISSUE THREAD

**Issue by hursey013** [18F/samhsa-prototype#43]
In the event that the vendor's endpoint is down or there are other technical issues, we should provide messaging to the user instead of the default "no results" message we currently have.

**Comment by hursey013** [comment]
@allisonnorman @amandacostello Do you have any suggestions for content for this page? Basically someone would arrive here if they initiated a search but for some reason something goes wrong getting the data back (the vendor's servers are down for example).

**Comment by allisonnorman** [comment]
What about using the 404 error language that we have today? (It's a slightly different version of the no results messaging). Thoughts @amandacostello?

**Comment by amandacostello** [comment]
Idea for content:

**Something's wrong on our side.**

We're having technical issues pulling up search results right now. The problem should be fixed soon, and in the meantime you can call XXX-XXXX (Helpline) or XXX-XXXX (Crisis Line) for immediate help.

**Comment by amandacostello** [comment]
THOUGH, even if they call the help line, can they still get help if the servers are down?

**Comment by Jkrzy** [comment]
@amandacostello great question! We've got confirmation from SAMHSA that the helpline is not impacted by availability of the existing TL. We can and should direct folks to call if we're unable to retrieve data.
