### ISSUE TITLE
remove site from federalist staging

### ISSUE THREAD

**Issue by amirbey** [18F/samhsa-prototype#441]
@hursey013  to:
- [x] remove site from federalistapp-staging.18f.gov
- [x] remove federalistapp-staging webhooks in GitHub - https://github.com/18F/samhsa-prototype/settings/hooks

**Comment by amirbey** [comment]
added to federalist staging only for testing of react-snap .... should be removed to prevent staging from occasionally sticking PR checks

**Comment by davemcorwin** [comment]
Removed from Federalist Staging

**Comment by allisonnorman** [comment]
@davemcorwin - Can we close the issue?

**Comment by davemcorwin** [comment]
@allisonnorman yes!
