### ISSUE TITLE
Render different meta image based on whether its homepage or subpage

### ISSUE THREAD

**Issue by hursey013** [18F/samhsa-prototype#448]
You can render the larger social sharing preview image by including:
```
          <meta
            property="og:image"
            content={`${process.env.REACT_APP_SITE_DOMAIN}/thumbnail-large.jpg`}
          />
          <meta name="twitter:card" content="summary_large_image" />
```
or a smaller one with:
```
          <meta
            property="og:image"
            content={`${process.env.REACT_APP_SITE_DOMAIN}/thumbnail.png`}
          />
          <meta name="twitter:card" content="summary" />
```

I did not have time to figure out how to only have the large display on the homepage and the small on sub pages, but since there is a cascading effect with react-helmet there is likely some way of including the proper meta tags where need be.

**Comment by Jkrzy** [comment]
Resolved in #443
