### ISSUE TITLE
Facility card option without map images

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#453]
@Jkrzy and @davemcorwin are digging into a limitation we have with generating static images from the Google API. There is a limit of 25k per day, which means that we could reach our max with ~2500 searches.

As they investigate potential workarounds, @austinhernandez - could you help by putting sharing a design for a facility card without the static map image, or do you have a previous design that you already created like this? This might need to be used for all cards, or potentially as a fallback option once the limit is reached. 

To be a bit more specific:
- The only asset that we may have issues generating is the static image
- Distance and a link to google maps (or, the distance hyperlinked to google maps) is still on the table.

**Comment by austinhernandez** [comment]
Mobile
![image](https://user-images.githubusercontent.com/23194720/66506916-35cdfa80-ea9c-11e9-999d-3e8e64907b65.png)

Desktop
![image](https://user-images.githubusercontent.com/23194720/66507081-89d8df00-ea9c-11e9-8425-4fa7326da90f.png)

**Comment by allisonnorman** [comment]
@austinhernandez You're so fast (and so good!) 

For desktop, do you recommend hyperlinking the distance or putting "get directions" on there in any way?

**Comment by austinhernandez** [comment]
Hey Allison! The address should be hyperlinked (#347) and be a different color. Maybe the changes got reverted?
