### ISSUE TITLE
Fine tune autocomplete implementation

### ISSUE THREAD

**Issue by Jkrzy** [18F/samhsa-prototype#455]
We're currently using a query delay of 100ms on our location autocomplete. This seems over-eager. Can it be delayed without impacting the experience? Increasing would save on cost and quota usage.

We should also investigate using sessions for each autocomplete session: https://developers.google.com/places/web-service/session-tokens

**Comment by Jkrzy** [comment]
@bpdesigns , are there any guidelines you're aware of in terms of upper limits on this type of input delay?

**Comment by bpdesigns** [comment]
@Jkrzy Digging into this a bit it seems like 100ms is what people are limit before a a visitor will notice any delay. We could try testing out 50ms if that would help.

**Comment by Jkrzy** [comment]
Thanks @bpdesigns, here's a preview instance with the value _doubled_ to 200ms. So the autocomplete doesn't make any suggestions until 200ms have elapsed since a value was entered into the input.

Give it a shot when you have a chance please.

https://cg-efcd7c90-b365-4336-8b87-6174f1975c99.app.cloud.gov/preview/18f/samhsa-prototype/autoc/

**Comment by Jkrzy** [comment]
Moving to sessions seems unnecessary as we're not performing a Places Details query once a user selects an autocomplete result. 

Given the increase in `debounce` we're also targeting less than 6 autocomplete requests to reach the desired place, which means its cheaper than sessions based billing.

**Comment by Jkrzy** [comment]
@allisonnorman, can you [take a look](https://github.com/18F/samhsa-prototype/issues/455#issuecomment-541099658) as well? ☝️

**Comment by allisonnorman** [comment]
Just to confirm, I'm testing by typing locations into the search field. I type quickly (as we all do), and do not notice a lag. I have tested it at varying speeds "what would it be like for my mom?" etc and don't notice a difference, honestly.  

@Jkrzy - Let me know if I should be testing this differently, or if there is anything about the preview link that would feel different than production. Otherwise, 👍 !

**Comment by bpdesigns** [comment]
@jkrzy I do notice a slowdown which is not ideal. I think we could do it for now if we need to but then would recommend going back to 100ms after the rush of publicity to the site.

**Comment by bpdesigns** [comment]
@Jkrzy this looks good to me. Go for it.
