### ISSUE TITLE
Create production Crazy Egg snapshots

### ISSUE THREAD

**Issue by Jkrzy** [18F/samhsa-prototype#472]
Required for: #344 

For release we should establish CE snapshots for each page of the TL.

https://crazyegg.com

Landing and search pages - 6 total to capture mobile and desktop
- [x] Mobile & desktop - landing page
- [ ] Mobile & desktop - results page
- [ ] Mobile & desktop - details page 

Content pages: Snapshots for EACH url - 26 total?
- [ ] Mobile & desktop - /content/treatment-options/types-of-treatment
- [ ] Mobile & desktop - /content/treatment-options/medications-used-in-treatment
- [ ] Mobile & desktop - /content/treatment-options/calling-a-facility
- [ ] Mobile & desktop - /content/treatment-options/what-happens-next
- [ ] Mobile & desktop - /content/treatment-options/who-provides-care
- [ ] Mobile & desktop - /content/paying-for-treatment/understanding-the-cost-of-treatment
- [ ] Mobile & desktop - /content/paying-for-treatment/if-you-have-insurance
- [ ] Mobile & desktop - /content/paying-for-treatment/if-you-dont-have-insurance
- [ ] Mobile & desktop - /content/understanding-addiction/addiction-can-affect-anyone
- [ ] Mobile & desktop - /content/understanding-addiction/recovery-starts-with-asking-for-help
- [ ] Mobile & desktop - /content/understanding-addiction/supporting-recovery-and-self-care
- [ ] Mobile & desktop - /content/understanding-mental-health/serious-mental-illness
- [ ] Mobile & desktop - /content/understanding-mental-health/know-the-warning-signs

Also TODO
- [x] Update `analytics.js` with new `CE_SNAPSHOT_NAME` value [#498]

**Comment by bpdesigns** [comment]
@Jkrzy @BrooklynHopkins This is how I would prioritize CE snapshots considering - 1. what we want to make sure is working now and 2. what would we learn from this that would impact further feature improvements?

**Initial Search** so we understand the initial experience 
- [ ]  Mobile & desktop - landing page
- [ ]  Mobile & desktop - results page

**Content pages linked from filter headers**  so we understand how they react to entering a new page from these links and if/what content it causes them to dig into further
- [ ] TREATMENT TYPE - https://findtreatmentbeta.18f.gov/content/treatment-options/types-of-treatment
- [ ] PAYMENT OPTIONS - https://findtreatmentbeta.18f.gov/content/paying-for-treatment/understanding-the-cost-of-treatment
- [ ] MEDICATION-ASSISTED TREATMENT (MAT) - https://findtreatmentbeta.18f.gov/content/treatment-options/medications-used-in-treatment

**Next steps in Search** so we understand if the content is laid out in a way people want to digest it and what parts of the page they think are interactive. (I'd also be open to putting this ahead of the CE for the content pages linked from filter headers - both seem useful for different reasons)
- [ ] Mobile & desktop - details page

**Comment by allisonnorman** [comment]
@Jkrzy - @davemcorwin held off on merging this as part of the launch-prep branch release: https://gsa-tts.slack.com/archives/CEGB4TU4S/p1572304777237200 - FYI

**Comment by Jkrzy** [comment]
Snapshots as specified by @bpdesigns [here](https://github.com/18F/samhsa-prototype/issues/472#issuecomment-545972909) have been created and scheduled to begin collecting 10/30 @ 6am EST.
