### ISSUE TITLE
Manual testing of social media unfurling

### ISSUE THREAD

**Issue by Jkrzy** [18F/samhsa-prototype#477]
Required for: #344 

Originally resolved in #443, we've confirmed functionality on Facebook and Slack. 

Prior to release and after removal of `robots.txt`,  manually test and confirm functionality on Twitter.

**Comment by allisonnorman** [comment]
Notes from our live testing session today (we should recheck these on Mon/Tues):
- Three content pages with no preview icons on Slack: If you have insurance, understanding the cost of treatment, and types of treatment
- Both versions work on Facebook
- No small content preview on twitter (Findtreatment.gov works)

**Comment by allisonnorman** [comment]
https://docs.google.com/spreadsheets/d/13XUZNNMlsDJmoDFJBdsjzFpo7HQudehN9xGShP6j1nI/edit#gid=0

**Comment by allisonnorman** [comment]
There's some inconsistency with Twitter on sub-pages but confirmed that the new card preview image renders on FB, twitter, and slack (both www. and findtreatment.gov)
