### ISSUE TITLE
Target SAMHSA google analytics

### ISSUE THREAD

**Issue by Jkrzy** [18F/samhsa-prototype#480]
Required for #344 

Push virtual pageviews and custom events to SAMHSA's google analytics property: `UA-70812959-1`

Also, revise Event category naming to match those already present in `UA-70812959-1`. Here's the complete list of those categories we're seeing as of Today. We won't need all of them.

```

errors
downloads
outbound link clicks
navigation
telephone clicks
search
mailto
data category
addthis
latest reports
forms
form
```

cc: @BrooklynHopkins

**Comment by davemcorwin** [comment]
We are currently using the following events, @BrooklynHopkins to which SAMHSA analytics events should they map?
- *Search*: 
- *Google Places API*: 
- *Form: filters*: 
- *Listing Data Report*:

**Comment by Jkrzy** [comment]
@davemcorwin, let's take a first pass at this ourselves. @BrooklynHopkins can weigh in on wherever we land. 

Our initial categories/labels, what we see now, were just my best guess at the time.
