### ISSUE TITLE
Inconsistent map linking from site

### ISSUE THREAD

**Issue by bpdesigns** [18F/samhsa-prototype#482]
### Issue
- when a site visitor clicks on the map link from the **Results** page the map shows up in a **new tab**
- when a site visitor clicks on the map link in "get directions" from the **Facility** page the map shows up in a **same tab**

## Suggestion
- make the action the same. 
- I would recommend sending people to a new tab. If you click the back button from google maps to the facility page, the "return to results" button goes away, which matters because if you click the back button again you are shown an reset search field with no location added

**Comment by allisonnorman** [comment]
@davemcorwin - How big of a lift is this? I don't think it was intentional and we should be consistent for launch if it's a straightforward change.
