### ISSUE TITLE
Home page linking issue - first "learn more" button

### ISSUE THREAD

**Issue by bpdesigns** [18F/samhsa-prototype#488]
tested on iPhone 7
### Current state 
- On the homepage navigate to the first "learn more" button
- Click sends you back to the top of the same page

### Desired state
- Click should send you down to the "what to expect" header in the same page.

**Comment by allisonnorman** [comment]
@bpdesigns - Weird, I can't reproduce on my iPhone X. Any chance you could try to screengrab this so we can debug?

**Comment by bpdesigns** [comment]
link to [video](https://drive.google.com/open?id=0B__dg4uQ4CvWT0FZQTF3THhDd0pxdGhsSWUxU0h2RkdqV1Jn) of it happening. Maybe its a screen size issue?

**Comment by allisonnorman** [comment]
Thank you! I'm able to reproduce it in Chrome for iPhone 6/7/8 Plus. This definitely seems like a bug. @davemcorwin - Can you take a look?

**Comment by davemcorwin** [comment]
huh, I am not able to reproduce this in Chrome, I can reproduce in Safari mobile and desktop though!

**Comment by davemcorwin** [comment]
ah, i see the issue. Currently, whenever the "page" changes we do a bunch of stuff including:
- setting the new page title
- announcement the change for screen readers
- setting focus and scrolling to the top h1/h2

It looks like this is also firing when following a "hash link" (a link to a location on the current page)  as well.

Correct me if I'm wrong, but my assumption is that we do NOT want to do any of the above stuff when following a link of this kind.

**Comment by bpdesigns** [comment]
Yes @davemcorwin for this link and for the "find treatment" link on the homepage. 

Whats interesting to me is that the "find treatment" link goes to the right place on the page when clicked - sends visitor to "search" button
