### ISSUE TITLE
Add "last reviewed" or equivalent to info content

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#492]
@amandacostello - Let's chat about this one when you get back

(Ref: https://gsa-tts.slack.com/archives/CEGB4TU4S/p1571843760121600)

**Comment by amandacostello** [comment]
An example of how NIH does it: https://ghr.nlm.nih.gov/about/reviewed-published-dates

For launch, maybe manually entering _October 2019_, but then figuring out if there's a way for the site to update this when a page itself is changed?

**Comment by amandacostello** [comment]
Good to go!
