### ISSUE TITLE
On mobile/tablet view, move filter section to top and move additional filters to advanced section

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#50]
Recommendation from Nick: 

*Issue:* The current filter placement in the both mobile and tablet-portrait is that they're out of view in the viewports, meaning there's a risk of an user not aware that they can filter the options when arriving at the results screen

*Suggestion:* Move the filter placement to the top; however, this means that filter options should be split into two groups: 1) Location, Payment, Type of Care; 2) `[Filter]`option expanding/displaying 'Age, programs, etc.'
**Note from Allison:** 
- "basic filters" on mobile/tablet-portrait: Location, payment options, type of care (see video for layout)
- "advanced filters" on mobile/tablet-portrait: everything else: existing advanced filters + age, gender, distance_

Note: For desktop view, the filter would have more options being visible whereas for mobile, an idea is to condense. A possible downside is that users on mobile / tablet-portrait may not be aware of the 'more filters' option. So we'll need to make this more explicit 

Rough prototype flow with filter located in the top for mobile and tablet-portrait (video): https://drive.google.com/open?id=1wMoIdO8ENEyG1CRHit9edD4q8zwGDIdG

**Comment by hursey013** [comment]
@allisonnorman I follow the thinking here, but I think we need to talk through the implementation a bit more. This approach conflicts with existing functionality and will require some refactoring so I want to make sure we have fully thought this out before getting started.
