### ISSUE TITLE
Update error messaging for launch

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#508]
We want to make the error messaging more welcoming, supportive, and encouraging in the event that we have issues with scaling during launch. 

Today it says: 

**Something is wrong on our side.**
_We're having technical issues right now. The problem should be fixed soon, and in the meantime SAMHSA's national helpline is available 24/7 and can assist you with treatment referrals and information._

We'd like to update it to encourage people to try searching again, because while it may be down now, it could work if they try it again. Something like "A lot of people are looking for help right now. Please try searching again in a few minutes. In the meantime SAMHSA's national helpline is available 24/7 and can assist you with treatment referrals and information." 

@amandacostello - Can you take a shot at this? I can make the change myself once the wording is ready. Thank you!

**Comment by amandacostello** [comment]
Message below for launch specific to high traffic; depending on traffic patterns (and other technical capabilities), it should go back to something more general later on. I kept the title the same so folks know it's not something they did!

**Something is wrong on our side.**
A lot of people are using the locator right now, and we're working hard to get things fixed. Try your search again in a few minutes, or call SAMHSA's national helpline at 1-800-662-HELP (4357). Helpline staff is available 24/7 and can help you with treatment information and referrals.
