### ISSUE TITLE
Remove static maps from results page

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#509]
We want to remove our dependency on the static maps API for launch. We need to do this before launch in order to not face issues with hitting the API limit of 25k requests per day.

@austinhernandez has shared a design proposal in [Slack]( (https://gsa-tts.slack.com/archives/CEGB4TU4S/p1572032826169800)), which replaces the static map images with another image.

@davemcorwin mentioned that the default state is the fallback, and that we make a separate call to Google and return the images if available. For launch, we should remove that step of checking and show this new version for all searches so that there is user experience continuity. 

Note for later: We may want to re-enable the static maps in the future once peak traffic has subsided.

**Comment by austinhernandez** [comment]
- Stop gap for the lack of static maps.
- No changes to the mobile site. 

![image](https://user-images.githubusercontent.com/23194720/67687099-27be1c00-f96e-11e9-8cc6-aec7a202fe43.png)

[mapless cards.zip](https://github.com/18F/samhsa-prototype/files/3779141/mapless.cards.zip)

**Comment by davemcorwin** [comment]
@austinhernandez you mentioned "No changes to the mobile site." but the current mobile view wraps the mileage text

![Screen Shot 2019-10-28 at 2 03 33 PM](https://user-images.githubusercontent.com/6662371/67717881-cb69f500-f98b-11e9-9d06-99af7fdba5d8.png)

Where should the icon be relative to the text in that case? I don't think we have room to expand the text horizontally...

![Screen Shot 2019-10-28 at 2 04 53 PM](https://user-images.githubusercontent.com/6662371/67717952-f8b6a300-f98b-11e9-8b56-992d2a822a0d.png)

**Comment by austinhernandez** [comment]
Sorry, Dave! I was talking about no change from the previous map-less design, not the current design 😞.  

The image is here: and it's also in that Sketch file above
 
![image](https://user-images.githubusercontent.com/23194720/67718260-c87bfe00-f9a5-11e9-9b76-2ffa2aae1f3a.png)

**Comment by austinhernandez** [comment]
Also, the Sketch file just contains the source for these PNGs, you don't need it for additional info.

**Comment by davemcorwin** [comment]
@austinhernandez thanks!!

The mobile view is quite a big change from the current implementation, would it be possible to just omit the map, expand the content on the rhs to be 100%, and add the distance text somewhere??

![Screen Shot 2019-10-28 at 2 26 58 PM](https://user-images.githubusercontent.com/6662371/67719450-133e4b80-f98f-11e9-95b2-6668ae06d0c2.png)

**Comment by davemcorwin** [comment]
Can you also let me know the name/source of the icon you're using?

**Comment by austinhernandez** [comment]
- That would be fine, if you could add the distance above the address.
- Icon is here: https://fontawesome.com/icons/directions?style=solid

**Comment by davemcorwin** [comment]
### Desktop
Icon TBD
![Screen Shot 2019-10-28 at 2 53 37 PM](https://user-images.githubusercontent.com/6662371/67721018-c0669300-f992-11e9-9cca-1aa5be84263c.png)

### Mobile
![Screen Shot 2019-10-28 at 2 53 30 PM](https://user-images.githubusercontent.com/6662371/67721019-c0669300-f992-11e9-8126-f08d63561001.png)
