### ISSUE TITLE
Add executive summary-level overview to Github repo for launch

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#510]

**Comment by allisonnorman** [comment]
@austinhernandez - Let's touch base on this on Monday too. Thanks!

**Comment by austinhernandez** [comment]
Here is the document: https://docs.google.com/document/d/1HeLE45FrzT16tM7ZXBzrhooO5O3SgT1M87CU86oYj-c/edit#heading=h.ly3xtql9nnc7

The only thing I want to confirm is that the GitHub project board will be public.

**Comment by allisonnorman** [comment]
@austinhernandez - Yes, the project board will be publicly accessible. The doc looks good!
