### ISSUE TITLE
Create an alternate homepage in the event that search functionality is unavailable

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#514]
If we run into longer-running issues with the API or Google maps (like, AWS is down or we have hit the cap on Google API spend), we want to have a version of the homepage ready to deploy that lets visitors know we are working on this without having them continue to try to search and get the error page. The idea is that we can have this ready to deploy if needed, and go back to normal state once the issue is resolved.

Ideas:
- Replace the search box with a message saying that functionality is limited and we're working on it + remove search from top nav
- Put up a box overlaying the search box and blocking any interaction with it + remove search from top nav

**Comment by austinhernandez** [comment]
![image](https://user-images.githubusercontent.com/23194720/67716804-d8dea980-f9a2-11e9-8ef0-97dbb3c3ca3e.png)

Words @amandacostello ?

**Comment by bpdesigns** [comment]
@austinhernandez @davemcorwin we should remove the "search for treatment" link in the nav

**Comment by amandacostello** [comment]
Words for the new box:

**For help finding treatment, call 1-800-662-HELP (4357)**

We're having technical issues right now, but are working hard to get things working again soon. In the meantime, SAMHSA's national helpline is available 24/7 and can help you with treatment referrals and information.

**Comment by Jkrzy** [comment]
Prepared in #533
