### ISSUE TITLE
www.findtreatment.gov needs to redirect to FindTreatment.gov

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#518]
Google is indexing www.findtreatment.gov, which is not whitelisted by the APIs, so therefore no one can search. 

Also, the same thing would happen if someone went to www.findtreatment.gov directly (which is likely because people are used to doing this). 

We should redirect www.findtreatment.gov to FindTreatment.gov, which should be our canonical URL.

**Comment by allisonnorman** [comment]
@davemcorwin - Good to close this?

**Comment by davemcorwin** [comment]
we're still trying to get it redirected... we just have a fallback in place now.

**Comment by Jkrzy** [comment]
On hold for now
