### ISSUE TITLE
Swap out social preview image

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#527]
Sondra asked if we could swap out one of the images on the social preview image for launch.

**Comment by austinhernandez** [comment]
Replaced younger person with older person. ![Twittercard](https://user-images.githubusercontent.com/23194720/67787260-a38b9780-fa46-11e9-9d15-b672a8bf1563.png)

Photoshop file is here on Drive:
https://drive.google.com/drive/folders/13HEnb8Kc-una0t-w8VjekYtJ6-WFmNMd
