### ISSUE TITLE
Search Results url 

### ISSUE THREAD

**Issue by bpdesigns** [18F/samhsa-prototype#536]
## current state
- complete a search on findtreatment.gov

### results 
- every search ends up with a url of "https://findtreatment.gov/results"

### problem 
- [what if] as a visitor to the site I want to share a list of results that I searched for with a friend. 
- if you share the url the person you share it with will get a blank search page.

**Comment by bpdesigns** [comment]
Not high priority for launch but relates to key tasks that Helpers would want to do. The use cases I've heard in testing has been for sharing individual facility details but I could imagine Helpers wanting to share a full search.

**Comment by allisonnorman** [comment]
Hey @bpdesigns - I think we have this idea captured in #178. If so, do you mind adding more detail there if it's the same and close this out?

**Comment by bpdesigns** [comment]
Thanks @allisonnorman yes. I'll close this and add more detail on the original issue.
