### ISSUE TITLE
Update no results and error messages

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#55]
**1. No results messaging**
Headline: "This search didn’t find any providers near you.

Please try expanding your search by applying less filters, like your ZIP code and the type of treatment you need. 

If you need assistance, our national helpline is available 24/7 and can assist you with treatment referrals and information. Call 1-800-662-HELP (4357) _(tel linked)_ to speak to someone."

Note: Amanda suggested not using the blue helpline phone # button on the no results pages. At a quick glance, someone may interpret that as having to call someone rather than understanding that they can refine their results OR call someone if that's what they need. Instead, we'd like to have the phone number inline linked.  

**2. Error messaging (general errors/404)**
Headline "This page isn’t here, but we can get you help."
Subtitle "Our national helpline is available 24/7 and can assist you with treatment referrals and information."
Insert existing helpline # button (used on the no results messaging)

**Comment by Jkrzy** [comment]
@amandacostello, any thoughts on the language suggested above by @allisonnorman?
