### ISSUE TITLE
Add Crazy Egg script to prototype

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#60]
Brooklyn can share the snippet of code when you're ready. I think she needs to send it via email so I've asked for her to share the snippet or send the email (likely tomorrow).

**Comment by Jkrzy** [comment]
@BrooklynHopkins, send that our way whenever you have a moment. Thanks!

**Comment by Jkrzy** [comment]
Received this from @BrooklynHopkins last week, it is in our court to implement/test.

**Comment by Jkrzy** [comment]
Clarifying the pages we want to capture. Each will require its own `snapshot` in CE, 16 total to capture both desktop and mobile views. 

cc: @allisonnorman @bpdesigns

@BrooklynHopkins , how many snapshots should we limit ourselves to so as to not impact other SAMHSA efforts

Desktop
- [ ]  Landing page
- [ ]  Results page
- [ ]  Details page
- [ ]  404 page
- [ ]  No search results page
- [ ] Understanding addiction
- [ ] Treatment Options
- [ ] Paying for treatment

Mobile
- [ ]  Landing page
- [ ]  Results page
- [ ]  Details page
- [ ]  404 page
- [ ]  No search results page
- [ ] Understanding addiction
- [ ] Treatment Options
- [ ] Paying for treatment

**Comment by BrooklynHopkins** [comment]
Nope we can do 8 – you can set up snapshots to capture mobile tablet and desktop separately! ☺

**Comment by Jkrzy** [comment]
Initial version is up and running on the prototype.
