### ISSUE TITLE
Remove links or references to features that we're not supporting in the prototype / or update

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#61]
We can wait until later in the week once the content is in place but creating an issue to track this. I'm thinking specifically of things like print view and updating/hyperlinking and removing links in the footer. We can see where we land in a couple days and then make a list of what to remove and update.

**Comment by Jkrzy** [comment]
@allisonnorman , do we have an inventory/list of these as output from the working session earlier today?

**Comment by allisonnorman** [comment]
I made most of the changes from our audit session in https://github.com/18F/samhsa-prototype/pull/78. Closing this as it was meant to be a placeholder.
