### ISSUE TITLE
Change colors for helpline callout and beta banner

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#79]
Story from Nick:

Story: As a user, I would like these to be more clear in their purpose. Also, in general, the header to be more visually calm:
Because it is red, the current  “Need help…” element creates an assumption that the number would take them to the crisis line
Because the “Need help…” element is red, the yellow beta banner makes both combination of red and yellow looks like a McDonald’s brand

Proposal: See `GLOBAL - BETA BANNER / NEED HELP` section in https://gsa.invisionapp.com/share/J8SNVOVFU5E

- The 'Need Help' element is teal (Icon section is #0F4756 / “Need help…” section is #196986) - 'Beta Banner' has two color updates - Soft yellow (#F5E684) w/ teal

Acceptance Criteria: 
The “Need help…” element doesn’t imply that the number is a crisis line
The beta banner / “Need help…” doesn’t look like a McDonald’s branding. In addition, creates a more calm sense, but not too calm that it loses the purpose of beta banner being a Call-Out.

(Other variations in Invision that we considered)
Bright yellow (#F6E05E)  w/ teal
Bright peach (#FF1EE) w/ teal
Soft peach (#F3E8E2) w/ teal

Notes from Nick:
- I think the yellow makes it stands out / more announcement tone. Unlike the bright yellow, the soft yellow tones down a bit to make it feels more calm.
- For peach, it takes on a more humane, caring tone while retaining the medical feel.

Nick's doc: https://docs.google.com/document/d/1hoj6ZpJXIyrnz-jsKi1qRuEN9HvCag0MRLg0O8pyYek/edit

**Comment by allisonnorman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(Testing GH integration) Change colors for helpline callout and beta banner](https://trello.com/c/0HNky5U0/225-testing-gh-integration-change-colors-for-helpline-callout-and-beta-banner)

**Comment by nickttng** [comment]
@allisonnorman @hursey013 If it's helpful: To swap colors using Tailwind default (Similar to proposed custom colors)

**Helpline Call-out**
In `src/components/HelpLine.js` ...

- Phone icon background: Replace `bg-red-700` with `bg-teal-700`
- "Need help..." background: Replace `bg-red-800` with `bg-teal-800`

**Beta Banner**
In `src/components/Header.js`, replace ```<div css={tw`bg-yellow-400`}>``` with ```<div css={tw`bg-yellow-300`}>``` for softer yellow

Preview of localhost screenshot

![Screenshot_2019-07-16 Treatment Finder](https://user-images.githubusercontent.com/6327082/61322257-de88f880-a7d2-11e9-8ff8-95b452f5128d.png)
