### ISSUE TITLE
On facility cards, if website info is blank, remove website line

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#8]
Some facilities don't appear to have a website. Can we remove the website line if a URL does not exist? (See attached screen shot for an example)

![Screen Shot 2019-06-25 at 3 03 39 PM](https://user-images.githubusercontent.com/6900926/60136967-7a868d80-975a-11e9-84a9-6cf33acd9e61.png)

**Comment by hursey013** [comment]
Fixed with https://github.com/18F/samhsa-prototype/commit/21c0ff1c80ead3ae61c8c88dcad836c86722a5c9
