### ISSUE TITLE
Add active state to navigation

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#80]
As a user, I should see where I am on the site reflected in the top navigation so that I can understand how I can navigate throughout the site:
- When I am searching for treatment, I should see the "Searching for treatment" in top nav highlighted
- When I am reading the information content, I should see "Getting started" activated

**Comment by bpdesigns** [comment]
On the hover state for "Searching for treatment" and "Getting started" there should be _a color change and or bolding_ to give a clear indication that the text is a clickable link. 

@nickttng not sure if this is something you're working on or want to weigh in with UI design preferences.

**Comment by bpdesigns** [comment]
I would also add a hover state change that is visual on our logotype "home" button on the top left of the page. 

Adding this comment to this issue because the styling should match.

**Comment by nickttng** [comment]
@bpdesigns 

> On the hover state for "Searching for treatment" and "Getting started" there should be a color change and or bolding to give a clear indication that the text is a clickable link.

To kick off this discussion - Something like the 'Simple Link' states in this demo would work well, especially the bottom-border when hovering. For SAMHSA, the border would be thinner and color-tweaked to fit the SAMSHA visual style

> I would also add a hover state change that is visual on our "Treatment Locator" logotype home button on the top left of the page.

For this home "logotype" button, it could dim/fade a bit to display hover state.

**Comment by bpdesigns** [comment]
Those sound great @nickttng
