### ISSUE TITLE
Reword "all facilities are licensed" statement

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#81]
From our prototype audit: Re-word and update statement “all facilities are licensed” (true but could be misleading

**Comment by amandacostello** [comment]
All facilities are licensed by the state they're in, though license requirements differ by state. There is no federal licensing for facilities. 

(This may be too long, but it's a start!)

**Comment by allisonnorman** [comment]
Covered in PR #98 https://github.com/18F/samhsa-prototype/pull/98
