### ISSUE TITLE
Update labels for gender and age 

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#84]
We need to update the labels for gender and age on the filter section to clearly articulate what filtering by this will do for the user. Something like:
Ages accepted, Gender accepted

**Comment by allisonnorman** [comment]
I can make the changes once you're ready with the wording, @amandacostello!

**Comment by amandacostello** [comment]
I dig these! 
"Ages accepted"
"Genders accepted" 

Maybe some note about how the genders will include co-ed?

**Comment by allisonnorman** [comment]
Updated the labels in PR #78. @amandacostello - let's track the gender/co-ed messaging separately.
