### ISSUE TITLE
Consider supporting a way to reset filters

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#9]
I'm wondering if it makes sense to allow users to reset filters (remove applied filters) on the results page. I think this could help when people have no or limited results, or want to refine the results differently given that we're asking them to select specific filters one at a time.

It could be as simple as a reset link near the top or by the update filters button. If others agree, we can also get design feedback. Attached is an example from Redfin for reference. 
![Screen Shot 2019-06-25 at 3 09 01 PM](https://user-images.githubusercontent.com/6900926/60137339-71e28700-975b-11e9-83db-42432288a20c.png)

**Comment by el-mapache** [comment]
@allisonnorman @hursey013 Would resetting the filters also reset the search results on that page? 

This is the behavior seen on Redfin (for example), although that site preserves a base set of search results using the original location the user entered.

**Comment by allisonnorman** [comment]
@el-mapache - Great question. I think we should reset the search results with the exception of location (same behavior as Redfin). Is that feasible?

**Comment by el-mapache** [comment]
@allisonnorman yep, we can definitely clear all filters except for location! Thanks 😄
