### ISSUE TITLE
Add info-linked integrated content

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#99]
Consolidated list
- [ ] Add links to info content on filter section (payment options, type of care, MAT) - see screenshot for placement and links below
- [ ] Add links to info content on details page - see screenshot for placement 
- [ ] Add links on results page - see screenshot

_(Previous description)_
_- Link to "before you call" and/or "calling a facility" content on facility/details page (under CTA phone/web buttons)
- "Not sure" type links within filtering section for type of care, payment options, MAT, (gender?)
- Link info content on results page (before you call, calling a facility, etc?)
- Where else?_

**Comment by amandacostello** [comment]
Images of integrated content placement

![integratedcontent](https://user-images.githubusercontent.com/45800660/61368599-d1601e00-a853-11e9-8657-aca64d48340b.jpg)
![detailspage](https://user-images.githubusercontent.com/45800660/61368601-d1601e00-a853-11e9-8746-e0d43c0831d1.jpg)

*Link details*
* Payment options "Not Sure?" link: https://findtreatmentbeta.18f.gov/content/paying-for-treatment
* Type of Care "Not Sure?" link: https://findtreatmentbeta.18f.gov/content/treatment-options#types-of-treatment
* MAT link "What are the differences between these medications? https://findtreatmentbeta.18f.gov/content/treatment-options#medications-used-in-treatment
* "What to expect when you call" link: https://findtreatmentbeta.18f.gov/content/treatment-options#calling-a-facility

**Comment by amandacostello** [comment]
Homepage under "What to Expect"
"Treatment works, help is available, and people recover every day."

"What to Expect" landing page:
Lede: Treatment works, help is available, and people recover every day."

(Intro para)
Intro para: "Beginning recovery can be overwhelming and intimidating. While everyone's path to recovery is unique, there are certain things you can expect and be ready for when you start. 

There is help. From understanding more about addiction and treatment options, to being ready to navigate insurance and payment, this information can help you feel more confident as you take the next step to finding treatment.

**Comment by allisonnorman** [comment]
I'm going to pull the 'what to expect' into a separate issue as I'm working on that and don't want to do double duty. I'll edit this issue and link to the new one.

**Comment by allisonnorman** [comment]
Added the what to expect content-specific changes in #109.

**Comment by amandacostello** [comment]
![results-top](https://user-images.githubusercontent.com/45800660/61479507-9e07b700-a959-11e9-9595-274f021e4b48.png)

Content for the box, in 2 paragraphs so it doesn't smoosh up too much:

**Before you visit**
Before visiting a facility, call to make sure they have the services you need. [What to expect when you call.](https://findtreatmentbeta.18f.gov/content/treatment-options#calling-a-facility)

Not sure what you need? [Learn more about different types of treatment.](https://findtreatmentbeta.18f.gov/content/treatment-options#types-of-treatment) All facilities are licensed by their states, and provide assessments.
